[project]
name = 'LocalDAO'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.budget-tracking]
path = 'contracts/budget-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.community-governance]
path = 'contracts/community-governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.community-token]
path = 'contracts/community-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
